### ISSUE TITLE
Write is_expert to db

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/foldit-view-data#16]
As #10 but for the options table, tracking whether the entry comes from an expert or not.
Two ways to determine is_expert:
- Using the first row of the experts.csv file, which is sorted by the composite key of (uid, pid, timestamp) concatenated. All entries in this file describe experts
- Using the get_all_experts function directly, or copying/modifying that code

**Comment by lee-vivian** [comment]
> As #10 but for the options table, tracking whether the entry comes from an expert or not.
> Two ways to determine is_expert:
> 
> * Using the first row of the experts.csv file, which is sorted by the composite key of (uid, pid, timestamp) concatenated. All entries in this file describe experts
> * Using the get_all_experts function directly, or copying/modifying that code

I believe experts.csv only has two columns (uid, num highscores associated with that uid), which is sorted by the num highscores, and does not contain the pid or timestamp (unless the comment is referring to something else that I'm missing)

**Comment by joshmiller17** [comment]
Ah, you are correct. This should in fact make it easier to figure out experts, as it looks like you've already done.
