### ISSUE TITLE
centroid_stats uses too much CPU/mem

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/foldit-view-data#17]
Refactor the centroid_stats function to use significantly less CPU/memory. Current draft is very brute force and doesn't run easily.

Potential Leads:
- Faster compiler: https://pypy.org/
- Use a profiler to figure out what's taking so long

**Comment by joshmiller17** [comment]
going to ask advisers about optimization on Wednesday

**Comment by lee-vivian** [comment]
Replace commented out function and get std dev for each dimension of all views in the cluster (std dev of each dim column) => return as array of length = dim param or if dim = -1 do for all dimensions
centroid = observations  x dims
