### ISSUE TITLE
Update experiment details and put that data in Overleaf

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/foldit-view-data#46]
In the Data Collection section of Overleaf, update all of the numbers to have the correct information.

**Comment by lee-vivian** [comment]
All queries in print_experiment_details() use the options table, not rprp_puzzle_ranks, so we should be good there. I also ran the sql queries via sqlite3 in my terminal and confirmed that the numbers are the same; the numbers reported in the Data Collection section should be accurate.

**Comment by joshmiller17** [comment]
These queries need to use the options table joined on rprp_puzzle_ranks
