### ISSUE TITLE
Exploratory hierarchical agg. clustering

### ISSUE THREAD

**Issue by joshmiller17** [joshmiller17/foldit-view-data#8]
- [x] Remove all duplicates before clustering
- [x] Figure out how many samples can fit, subsample if need be
- [x] Figure out how to get number of clusters from dendrogram
- [x] Within each group, how many samples fall in each cluster? How many clusters does the group spread out over?

**Comment by joshmiller17** [comment]
Requires categorical options to be one-hot encoded first. See #12 as an example
TODO: make a function that exports DB as CSV using only binary / one-hot encoded vars

**Comment by lee-vivian** [comment]
Still having issues with hierarchical clustering in Orange even when using new binarized options table. Application will freeze and stop responding, even when attempting to calculate Distance for a table with a unique id and only 5 selected options columns.

**Comment by joshmiller17** [comment]
New plan: do it in Python. We can print out the information in a way that's just as helpful as a visualization.
